### ISSUE TITLE
TypeScript 7 rejects the side-effect import of globals.css

### ISSUE THREAD

**Issue by rheos** [rheos/foaf-next-site#8]
Dependabot #5 (typescript 5.8.3 -> 7.0.2) fails the type check added in #7:

```
src/app/layout.tsx(1,8): error TS2882: Cannot find module or type declarations
for side-effect import of './globals.css'.
```

TypeScript 7 no longer accepts an untyped side-effect CSS import. Needs a module declaration (a `css.d.ts` declaring `*.css`) or the equivalent compiler configuration, after which the bump should be re-runnable.

Not urgent. TypeScript 5 is fine and the build is green; this is only blocking the major.
